#!/bin/bash

set -euo pipefail

#TODO: we want to actually obey what tests we are given
if lsb_release -i | grep -qi suse ; then
	./test-builds.sh layer-00-bootstrap
	(cd libltdl; autoreconf -fi)
	./test-builds.sh layer-00-default layer-01-minimal layer-02-maximus
else
	./test-builds.sh $@
fi

