--- ubuntu-hirsute/Dockerfile
+++ ubuntu-hirsute/Dockerfile
@@ -35,6 +35,7 @@ RUN \
                libtool-bin \
                libxml2-dev \
                lsb-release \
+               m4 \
                make \
                nettle-dev \
                pkg-config \
