#!/bin/bash

# in the context of a centos-8+ docker image
[ -x /usr/bin/rsync ] || yum install -y rsync
basemirror=rsync://mirrors.ukfast.co.uk/ftp.centos.org
chroot=/home/jenkins/stream-install

[ -d "$chroot" ] && rm -rf "$chroot"

rpm --root $chroot --rebuilddb
# assumption: there is only one
rsync $basemirror/8-stream/BaseOS/x86_64/os/Packages/centos-stream-release-\* .
rpm --root $chroot --nodeps -i  centos-stream-release-*.rpm
yum --installroot $chroot update
yum --installroot $chroot install -y yum centos-stream-repos
(cd $chroot; tar -c -f ../centos-8-stream-root.tar.gz -z *)
#rm -rf "$chroot"
