name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 4 15 * *"   # on the 15th of each month

jobs:

  build:
    if: false   # disable for now

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
        name: Set up Qemu

      - uses: docker/setup-buildx-action@v3
        name: Set up Buildx

      - uses: actions/checkout@v2
        name: Check out sources

      - name: Build the Docker images
        run: |
          make all

  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      targets: ${{ steps.targets.outputs.targets }}

    steps:
      - uses: actions/checkout@v2
        name: Check out sources

      - name: Define targets
        id: targets
        run: |
          echo -n "targets=[" >> "$GITHUB_OUTPUT"
          make targets | grep -v gentoo | sed 's/- /, "/;s/$/"/' | tr -d '\n' | sed 's/^, //' >> "$GITHUB_OUTPUT"
          echo -n "]" >> "$GITHUB_OUTPUT"


  build-matrix:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.define-matrix.outputs.targets) }}

    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
        name: Set up Qemu

      - uses: docker/setup-buildx-action@v3
        name: Set up Buildx

      - uses: actions/checkout@v2
        name: Check out sources

      - name: Build the Docker images
        run: |
          make ${{ matrix.target }} 2>&1 | tee ${{ matrix.target }}-buildlog.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-buildlog.txt
          path: ${{ matrix.target }}-buildlog.txt
          retention-days: 30

